project_id = "oxrfslyuzcgxacomgzgw"

[functions.process-receipt]
verify_jwt = true

[functions.suggest-passive-income]
verify_jwt = true

[functions.analyze-contract]
verify_jwt = true

[functions.process-bank-statement]
verify_jwt = true

[functions.analyze-bank-statement]
verify_jwt = true

[functions.optimize-taxes]
verify_jwt = true

[functions.optimize-rrsp-tfsa]
verify_jwt = true

[functions.predict-expenses]
verify_jwt = true

[functions.app-assistant]
verify_jwt = true

[functions.suggest-tags]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
