project_id = "oxrfslyuzcgxacomgzgw"

[functions.process-receipt]
verify_jwt = true

[functions.suggest-passive-income]
verify_jwt = true

[functions.analyze-contract]
verify_jwt = true

[functions.process-bank-statement]
verify_jwt = true

[functions.analyze-bank-statement]
verify_jwt = true
